spine:
  defaults:
    bgp_as: 65100
    loopback_ipv4_pool: 10.0.254.0/24
    bgp_default:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
    mlag: false
    evpn_route_servers: [DCI]
  nodes:
    spine1-DC1:
      id: 11
      mgmt_ip: 172.16.20.6/24
    spine2-DC1:
      id: 12
      mgmt_ip: 172.16.20.7/24

l3leaf:
  defaults:
    bgp_as: 65101-65190
    loopback_ipv4_pool: 10.0.254.0/24
    vtep_loopback_ipv4_pool: 10.0.255.0/24
    uplink_ipv4_pool: 192.168.0.0/24
    uplink_interfaces: [Eth1, Eth2]
    uplink_switches: [spine1, spine2]
    mlag: true
    mlag_interfaces: [eth3, eth4]
    mlag_peer_ipv4_pool: 192.168.90.0/24
    mlag_peer_l3_ipv4_pool: 192.168.91.0/24
    virtual_router_mac_address: ca:fe:ca:fe:ca:fe
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384 